package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"notes-app/graph/model"
	"notes-app/internal/auth"
	apperrors "notes-app/pkg/errors"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	return r.AuthService.Register(ctx, input.Name, input.Email, input.Password)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	return r.AuthService.Login(ctx, input.Email, input.Password)
}

// LoginWithGoogle is the resolver for the loginWithGoogle field.
func (r *mutationResolver) LoginWithGoogle(ctx context.Context, idToken string) (*model.AuthPayload, error) {
	return r.AuthService.LoginWithGoogle(ctx, idToken)
}

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input model.NewNote) (*model.Note, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, apperrors.Unauthorized("authentication required")

	}
	return r.NoteService.CreateNote(ctx, userID, input.Title, input.Content)
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, input model.UpdateNoteInput) (*model.Note, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, apperrors.Unauthorized("authentication required")
	}
	return r.NoteService.UpdateNote(ctx, userID, id, input.Title, input.Content)
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (bool, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return false, apperrors.Unauthorized("authentication required")
	}
	return r.NoteService.DeleteNote(ctx, userID, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, apperrors.Unauthorized("authentication required")
	}
	return r.AuthService.Me(ctx, userID)
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context) ([]*model.Note, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, apperrors.Unauthorized("authentication required")
	}
	return r.NoteService.ListNotes(ctx, userID)
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*model.Note, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, apperrors.Unauthorized("authentication required")
	}
	return r.NoteService.GetNote(ctx, userID, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
