type User {
  id: ID!
  name: String!
  email: String!
  createdAt: String!
}

type AuthPayload {
  token: String!
  user: User!
}

input RegisterInput {
  name: String!
  email: String!
  password: String!
}

input LoginInput {
  email: String!
  password: String!
}

type Note {
  id: ID!
  title: String!
  content: String!
  createdAt: String!
  updatedAt: String!
}

input NewNote {
  title: String!
  content: String!
}

input UpdateNoteInput {
  title: String
  content: String
}

type Query {
  me: User
  notes: [Note!]!
  note(id: ID!): Note
}

type Mutation {
  register(input: RegisterInput!): AuthPayload!
  login(input: LoginInput!): AuthPayload!
  loginWithGoogle(idToken: String!): AuthPayload!
  createNote(input: NewNote!): Note!
  updateNote(id: ID!, input: UpdateNoteInput!): Note!
  deleteNote(id: ID!): Boolean!
}
